<?php

return [
    'list' => [
        'Kojima Productions',
        'FromSoftware',
        'Naughty Dog',
        'Rockstar Games',
        'Ubisoft',
        'Bethesda Game Studios',
        'Santa Monica Studio',
        'Insomniac Games',
        'Square Enix',
        'Capcom',
        'BioWare',
        '343 Industries',
        'Bungie',
        'Respawn Entertainment',
        'Remedy Entertainment',
        'Larian Studios',
        'Game Freak',
        'Monolith Soft',
        'PlatinumGames',
        'Valve Corporation',
        'id Software',
        'Arkane Studios',
        'Guerrilla Games',
        'Obsidian Entertainment',
        'Supergiant Games',
        'Tango Gameworks',
        'Housemarque',
        'Treyarch',
        'Atlus',
        'Mojang',
        'Nintendo',
        'CD Projekt',
        'EA Sports',
        'miHoYo',
        'ConcernedApe',
        'Epic Games',
        'InnerSloth',
        'Studio MDHR',
        'Riot Games',
        'Re-Logic',
        'Blizzard Entertainment',
        'Hello Games',
        'Maddy Makes Games',
    ],
];
