<?php

return [
    [
        'title' => 'Death Stranding',
        'description' => 'In un futuro post-apocalittico, un evento catastrofico noto come il "Death Stranding" ha sconvolto il confine tra il mondo dei vivi e quello dei morti, portando alla comparsa di creature ultraterrene e alla frammentazione della società. I giocatori vestono i panni di Sam Porter Bridges, un corriere incaricato di attraversare territori desolati per consegnare risorse vitali e ristabilire connessioni tra le comunità isolate. Il gioco combina elementi di esplorazione, gestione delle risorse e una narrazione profonda, offrendo un\'esperienza unica che riflette sulle tematiche della connessione umana e dell\'isolamento.',
        'release_date' => '2019-11-08',
        'developer' => 'Kojima Productions',
        'consoles' => ['PlayStation 4', 'PlayStation 5', 'PC'],
        'genres' => ['action', 'adventure'],
        'cover_image' => 'games/covers/death-stranding.jpg',
    ],
    [
        'title' => 'Persona 5 Royal',
        'description' => 'Persona 5 Royal è un\'espansione del celebre JRPG che segue le vicende di un gruppo di studenti delle superiori noti come i "Phantom Thieves of Hearts". Utilizzando poteri soprannaturali, questi giovani eroi si infiltrano nei "Palazzi" del subconscio per cambiare i cuori degli adulti corrotti. Il gioco offre una combinazione di vita scolastica, esplorazione di dungeon e combattimenti a turni, arricchita da nuove trame, personaggi e finali alternativi. Ambientato in una vibrante Tokyo, il titolo esplora temi di giustizia, amicizia e identità personale, offrendo un\'esperienza coinvolgente e stilisticamente unica.',
        'release_date' => '2020-03-31',
        'developer' => 'Atlus',
        'consoles' => ['PlayStation 4', 'Nintendo Switch', 'PC', 'Xbox One', 'Xbox Series X'],
        'genres' => ['rpg', 'adventure'],
        'cover_image' => 'games/covers/persona-5-royal.jpg',
    ],
    [
        'title' => 'Minecraft',
        'description' => 'Minecraft è un gioco sandbox che permette ai giocatori di esplorare un mondo tridimensionale generato proceduralmente, composto da blocchi e creature. I giocatori possono raccogliere risorse, costruire strutture, esplorare caverne e combattere creature ostili. Il gioco supporta diverse modalità, tra cui Sopravvivenza, dove i giocatori devono gestire fame e salute, e Creativa, che consente costruzioni illimitate. Con un sistema di crafting articolato e la possibilità di modificare l\'ambiente, Minecraft promuove la creatività e l\'ingegno. La sua comunità attiva ha contribuito a una vasta gamma di mod, espandendo ulteriormente le possibilità di gioco.',
        'release_date' => '2011-11-18',
        'developer' => 'Mojang',
        'consoles' => ['PC', 'Xbox One', 'PlayStation 4', 'Nintendo Switch', 'Mobile'],
        'genres' => ['sandbox', 'survival'],
        'cover_image' => 'games/covers/minecraft.jpg',
    ],
    [
        'title' => 'Elden Ring',
        'description' => 'Elden Ring è un action RPG ambientato in un vasto mondo aperto noto come le Terre Intermedie. I giocatori assumono il ruolo di un Tarnished, un esiliato chiamato a riunire i frammenti dell\'Elden Ring per diventare il nuovo Elden Lord. Il gioco combina combattimenti impegnativi, esplorazione libera e una narrativa profonda, frutto della collaborazione tra Hidetaka Miyazaki e George R.R. Martin. Le sei regioni principali offrono ambientazioni uniche, dungeon intricati e boss formidabili. Con un sistema di personalizzazione dettagliato e una varietà di armi e magie, Elden Ring offre un\'esperienza coinvolgente e gratificante per i fan del genere.',
        'release_date' => '2022-02-25',
        'developer' => 'FromSoftware',
        'consoles' => ['PC', 'PlayStation 4', 'PlayStation 5', 'Xbox One', 'Xbox Series X'],
        'genres' => ['rpg', 'action', 'adventure'],
        'cover_image' => 'games/covers/elden-ring.jpg',
    ],
    [
        'title' => 'The Legend of Zelda: Breath of the Wild',
        'description' => 'In The Legend of Zelda: Breath of the Wild, i giocatori esplorano un vasto mondo aperto nei panni di Link, risvegliatosi dopo un sonno di cento anni per affrontare la minaccia di Calamity Ganon. Il gioco rompe con le convenzioni della serie, offrendo una libertà senza precedenti nell\'esplorazione e nella risoluzione dei puzzle. I giocatori possono scalare montagne, cucinare pasti, affrontare nemici e risolvere enigmi in oltre 100 santuari sparsi per Hyrule. Con un sistema fisico realistico e una narrazione non lineare, il titolo è stato acclamato per la sua innovazione e profondità.',
        'release_date' => '2017-03-03',
        'developer' => 'Nintendo',
        'consoles' => ['Nintendo Switch'],
        'genres' => ['action', 'adventure'],
        'cover_image' => 'games/covers/the-legend-of-zelda-breath-of-the-wild.jpg',
    ],
    [
        'title' => 'Halo Infinite',
        'description' => 'Halo Infinite continua le avventure del Master Chief in un mondo aperto ambientato su Zeta Halo. Dopo la sconfitta dell\'UNSC da parte dei Banished, i giocatori devono esplorare l\'anello per svelare i misteri di Cortana e affrontare nuove minacce. Il gioco offre una campagna espansiva con una varietà di missioni e un sistema di progressione flessibile. Il multiplayer gratuito introduce nuove modalità e mappe, mantenendo l\'essenza classica della serie. Con una combinazione di narrativa coinvolgente e gameplay dinamico, Halo Infinite rappresenta un\'evoluzione significativa per il franchise.',
        'release_date' => '2021-12-08',
        'developer' => '343 Industries',
        'consoles' => ['Xbox One', 'Xbox Series X', 'PC'],
        'genres' => ['shooter', 'action'],
        'cover_image' => 'games/covers/halo-infinite.jpg',
    ],
    [
        'title' => 'Animal Crossing: New Horizons',
        'description' => 'In Animal Crossing: New Horizons, i giocatori si trasferiscono su un\'isola deserta grazie a un pacchetto vacanze offerto da Tom Nook. L\'obiettivo è trasformare l\'isola in una comunità fiorente, raccogliendo risorse, costruendo infrastrutture e interagendo con abitanti antropomorfi. Il gioco si svolge in tempo reale, con eventi stagionali e festività che arricchiscono l\'esperienza. La personalizzazione dell\'isola e della propria abitazione è al centro del gameplay, offrendo un\'esperienza rilassante e gratificante che ha conquistato milioni di giocatori in tutto il mondo.',
        'release_date' => '2020-03-20',
        'developer' => 'Nintendo',
        'consoles' => ['Nintendo Switch'],
        'genres' => ['simulation', 'sandbox'],
        'cover_image' => 'games/covers/animal-crossing-new-horizons.jpg',
    ],
    [
        'title' => 'God of War Ragnarok',
        'description' => 'God of War Ragnarök segue le vicende di Kratos e suo figlio Atreus mentre affrontano le conseguenze delle loro azioni e si preparano all\'inevitabile fine del mondo, il Ragnarök. Ambientato nei Nove Regni della mitologia norrena, il gioco offre combattimenti intensi, enigmi ambientali e una narrazione emotiva. I giocatori esplorano paesaggi mozzafiato, affrontano divinità e mostri mitologici, e scoprono la verità sul passato di Atreus. Con una combinazione di azione frenetica e momenti toccanti, il titolo conclude la saga norrena con maestria.',
        'release_date' => '2022-11-09',
        'developer' => 'Santa Monica Studio',
        'consoles' => ['PlayStation 4', 'PlayStation 5'],
        'genres' => ['action', 'adventure'],
        'cover_image' => 'games/covers/god-of-war-ragnarok.jpg',
    ],
    [
        'title' => 'Cyberpunk 2077',
        'description' => 'Cyberpunk 2077 è un RPG d\'azione ambientato nella metropoli futuristica di Night City. I giocatori vestono i panni di V, un mercenario alla ricerca dell\'immortalità, coinvolto in una trama complessa che esplora temi di tecnologia, potere e identità. Il gioco offre una vasta gamma di opzioni di personalizzazione, missioni ramificate e un mondo aperto ricco di dettagli. Nonostante un lancio controverso, gli aggiornamenti successivi hanno migliorato l\'esperienza, rendendo Cyberpunk 2077 un titolo ambizioso che offre una visione immersiva di un futuro distopico.',
        'release_date' => '2020-12-10',
        'developer' => 'CD Projekt',
        'consoles' => ['PC', 'PlayStation 4', 'PlayStation 5', 'Xbox One', 'Xbox Series X'],
        'genres' => ['rpg', 'action'],
        'cover_image' => 'games/covers/cyberpunk-2077.jpg',
    ],
    [
        'title' => 'Super Mario Odyssey',
        'description' => 'In Super Mario Odyssey, Mario intraprende un viaggio attraverso mondi diversi per salvare la Principessa Peach da Bowser, che intende sposarla contro la sua volontà. Accompagnato dal suo nuovo alleato Cappy, un cappello senziente, Mario acquisisce la capacità di "possedere" oggetti e creature, utilizzandoli per superare ostacoli e risolvere enigmi. Il gioco introduce meccaniche innovative e livelli ricchi di segreti, offrendo un\'esperienza fresca e coinvolgente che celebra l\'eredità della serie Super Mario.',
        'release_date' => '2017-10-27',
        'developer' => 'Nintendo',
        'consoles' => ['Nintendo Switch'],
        'genres' => ['platform', 'adventure'],
        'cover_image' => 'games/covers/super-mario-odyssey.jpg',
    ],
    [
        'title' => 'Hades',
        'description' => 'Hades è un roguelike action RPG sviluppato da Supergiant Games. I giocatori vestono i panni di Zagreus, figlio di Ade, nel suo tentativo di fuggire dagli Inferi e raggiungere il Monte Olimpo. Il gioco combina combattimenti frenetici con una narrazione profonda, offrendo dialoghi dinamici e una progressione che si evolve ad ogni tentativo di fuga. Con uno stile artistico distintivo e una colonna sonora coinvolgente, Hades offre un\'esperienza unica che ha ricevuto numerosi riconoscimenti.',
        'release_date' => '2020-09-17',
        'developer' => 'Supergiant Games',
        'consoles' => ['PC', 'Nintendo Switch', 'PlayStation 4', 'PlayStation 5', 'Xbox One'],
        'genres' => ['roguelike', 'action'],
        'cover_image' => 'games/covers/hades.jpg',
    ],
    [
        'title' => 'FIFA 23',
        'description' => 'FIFA 23 è l\'ultima edizione della celebre serie calcistica di EA Sports. Il gioco introduce la tecnologia HyperMotion2, che migliora l\'animazione e la fluidità del gameplay. Con oltre 19.000 giocatori, 700 squadre e 100 stadi, offre un\'esperienza autentica del calcio mondiale. Per la prima volta, include squadre femminili di club e supporta il cross-play tra diverse piattaforme. Le modalità Ultimate Team, Carriera e VOLTA sono state ulteriormente perfezionate, offrendo ai giocatori una varietà di esperienze calcistiche.',
        'release_date' => '2022-09-30',
        'developer' => 'EA Sports',
        'consoles' => ['PC', 'PlayStation 4', 'PlayStation 5', 'Xbox One', 'Xbox Series X'],
        'genres' => ['sports'],
        'cover_image' => 'games/covers/fifa-23.jpg',
    ],
    [
        'title' => 'Genshin Impact',
        'description' => 'Genshin Impact è un action RPG open-world sviluppato da miHoYo. Ambientato nel mondo fantastico di Teyvat, i giocatori esplorano sette nazioni uniche, ciascuna ispirata a diverse culture. Il gioco offre un sistema di combattimento basato su elementi, permettendo combinazioni strategiche tra personaggi. Con una grafica mozzafiato, una colonna sonora orchestrale e aggiornamenti regolari che introducono nuove storie e personaggi, Genshin Impact ha conquistato milioni di giocatori in tutto il mondo.',
        'release_date' => '2020-09-28',
        'developer' => 'miHoYo',
        'consoles' => ['PC', 'PlayStation 4', 'PlayStation 5', 'Mobile'],
        'genres' => ['rpg', 'action'],
        'cover_image' => 'games/covers/genshin-impact.jpg',
    ],
    [
        'title' => 'Sekiro: Shadows Die Twice',
        'description' => 'Sekiro: Shadows Die Twice è un action-adventure sviluppato da FromSoftware. Ambientato in un Giappone feudale immaginario, i giocatori controllano Wolf, un shinobi in missione per salvare il suo giovane signore. Il gioco si distingue per il suo sistema di combattimento basato sulla postura e la parata, richiedendo precisione e tempismo. Con una narrazione profonda e un mondo ricco di dettagli, Sekiro offre una sfida intensa che ha ricevuto numerosi premi, incluso il Game of the Year.',
        'release_date' => '2019-03-22',
        'developer' => 'FromSoftware',
        'consoles' => ['PC', 'PlayStation 4', 'Xbox One'],
        'genres' => ['action', 'adventure'],
        'cover_image' => 'games/covers/sekiro-shadows-die-twice.jpg',
    ],
    [
        'title' => 'Stardew Valley',
        'description' => 'Stardew Valley è un simulatore di vita agricola sviluppato da ConcernedApe. I giocatori ereditano una fattoria trascurata e lavorano per riportarla al suo antico splendore. Oltre alla coltivazione, il gioco offre pesca, artigianato, esplorazione di miniere e interazioni sociali con gli abitanti del villaggio. Con uno stile pixel art affascinante e una colonna sonora rilassante, Stardew Valley offre un\'esperienza coinvolgente che celebra la vita semplice e la comunità.',
        'release_date' => '2016-02-26',
        'developer' => 'ConcernedApe',
        'consoles' => ['PC', 'PlayStation 4', 'Xbox One', 'Nintendo Switch', 'Mobile'],
        'genres' => ['simulation', 'rpg'],
        'cover_image' => 'games/covers/stardew-valley.jpg',
    ],
    [
        'title' => 'Fortnite',
        'description' => 'Fortnite è un videogioco online sviluppato da Epic Games, noto per la sua modalità Battle Royale in cui 100 giocatori competono per essere l\'ultimo sopravvissuto. Il gioco combina elementi di costruzione, combattimento e strategia, offrendo un\'esperienza dinamica e in continua evoluzione. Con eventi live, collaborazioni con franchise famosi e una vasta gamma di modalità di gioco, Fortnite è diventato un fenomeno culturale globale.',
        'release_date' => '2017-07-25',
        'developer' => 'Epic Games',
        'consoles' => ['PC', 'PlayStation 4', 'PlayStation 5', 'Xbox One', 'Xbox Series X', 'Nintendo Switch'],
        'genres' => ['battle_royale', 'shooter'],
        'cover_image' => 'games/covers/fortnite.jpg',
    ],
    [
        'title' => 'Among Us',
        'description' => 'Among Us è un gioco multiplayer di deduzione sociale sviluppato da Innersloth. Ambientato in una navicella spaziale, i giocatori assumono il ruolo di membri dell\'equipaggio o impostori. Gli impostori cercano di eliminare gli altri senza essere scoperti, mentre gli altri devono completare compiti e identificare i colpevoli. Con un gameplay semplice ma coinvolgente, Among Us ha guadagnato popolarità grazie alla sua enfasi sulla comunicazione e la collaborazione.',
        'release_date' => '2018-06-15',
        'developer' => 'InnerSloth',
        'consoles' => ['PC', 'Mobile', 'Nintendo Switch'],
        'genres' => ['party', 'strategy'],
        'cover_image' => 'games/covers/among-us.jpg',
    ],
    [
        'title' => 'Cuphead',
        'description' => 'Cuphead è un gioco run and gun sviluppato da Studio MDHR, ispirato ai cartoni animati degli anni \'30. I giocatori controllano Cuphead o Mugman mentre affrontano una serie di boss impegnativi per saldare un debito con il diavolo. Il gioco è noto per la sua grafica disegnata a mano, animazioni fluide e colonna sonora jazz. Con una difficoltà elevata e uno stile artistico unico, Cuphead offre un\'esperienza nostalgica e stimolante.',
        'release_date' => '2017-09-29',
        'developer' => 'Studio MDHR',
        'consoles' => ['PC', 'Xbox One', 'Nintendo Switch', 'PlayStation 4'],
        'genres' => ['platform', 'action'],
        'cover_image' => 'games/covers/cuphead.jpg',
    ],
    [
        'title' => 'Dark Souls III',
        'description' => 'Dark Souls III è un action RPG sviluppato da FromSoftware, noto per la sua difficoltà impegnativa e il mondo oscuro e interconnesso. I giocatori esplorano il regno di Lothric, affrontando nemici formidabili e boss epici. Il gioco offre un sistema di combattimento profondo, una vasta gamma di armi e magie, e una narrativa criptica che i giocatori devono scoprire attraverso l\'esplorazione. Dark Souls III conclude la trilogia con una combinazione di sfida e atmosfera coinvolgente.',
        'release_date' => '2016-04-12',
        'developer' => 'FromSoftware',
        'consoles' => ['PC', 'PlayStation 4', 'Xbox One'],
        'genres' => ['rpg', 'action'],
        'cover_image' => 'games/covers/dark-souls-iii.jpg',
    ],
    [
        'title' => 'League of Legends',
        'description' => 'League of Legends è un MOBA sviluppato da Riot Games, in cui due squadre di cinque giocatori competono per distruggere la base avversaria. Ogni giocatore controlla un "campione" con abilità uniche, e il gioco richiede strategia, coordinazione e abilità. Con una vasta gamma di campioni, modalità di gioco e una scena competitiva globale, League of Legends è diventato uno dei giochi più popolari e influenti nel panorama degli eSports.',
        'release_date' => '2009-10-27',
        'developer' => 'Riot Games',
        'consoles' => ['PC'],
        'genres' => ['strategy', 'mmo'],
        'cover_image' => 'games/covers/league-of-legends.jpg',
    ],
    [
        'title' => 'The Witcher 3: Wild Hunt',
        'description' => 'In The Witcher 3: Wild Hunt, i giocatori vestono i panni di Geralt di Rivia, un cacciatore di mostri professionista conosciuto come Witcher. Ambientato in un vasto mondo aperto ricco di dettagli, il gioco offre una narrazione profonda e ramificata, con missioni principali e secondarie che influenzano il destino dei personaggi e del mondo stesso. Il sistema di combattimento combina spade, magia e alchimia, permettendo ai giocatori di affrontare una varietà di creature e nemici. Con una grafica mozzafiato, una colonna sonora evocativa e una trama coinvolgente, The Witcher 3 è considerato uno dei migliori RPG di tutti i tempi.',
        'release_date' => '2015-05-19',
        'developer' => 'CD Projekt',
        'consoles' => ['PC', 'PlayStation 4', 'Xbox One', 'Nintendo Switch'],
        'genres' => ['rpg', 'action'],
        'cover_image' => 'games/covers/the-witcher-3-wild-hunt.jpg',
    ],
    [
        'title' => 'Red Dead Redemption 2',
        'description' => 'Ambientato nel 1899, Red Dead Redemption 2 segue le vicende di Arthur Morgan, membro della banda Van der Linde, in un\'America in trasformazione. Il gioco offre un mondo aperto vasto e dettagliato, dove i giocatori possono cacciare, pescare, interagire con NPC e affrontare missioni principali e secondarie. La narrazione profonda esplora temi di lealtà, redenzione e il declino del selvaggio West. Con una grafica mozzafiato e una colonna sonora coinvolgente, il titolo è considerato uno dei capolavori di Rockstar Games.',
        'release_date' => '2018-10-26',
        'developer' => 'Rockstar Games',
        'consoles' => ['PC', 'PlayStation 4', 'Xbox One'],
        'genres' => ['adventure', 'action'],
        'cover_image' => 'games/covers/red-dead-redemption-2.jpg',
    ],
    [
        'title' => 'Horizon Forbidden West',
        'description' => 'In Horizon Forbidden West, i giocatori vestono nuovamente i panni di Aloy, una cacciatrice in un mondo post-apocalittico dominato da macchine. Il gioco espande l\'universo introdotto in Horizon Zero Dawn, offrendo nuove regioni da esplorare, creature meccaniche più pericolose e una trama avvincente. Con un sistema di combattimento migliorato, nuove abilità e un mondo ricco di dettagli, il titolo offre un\'esperienza immersiva che combina esplorazione, azione e narrazione profonda.',
        'release_date' => '2022-02-18',
        'developer' => 'Guerrilla Games',
        'consoles' => ['PlayStation 4', 'PlayStation 5'],
        'genres' => ['action', 'adventure'],
        'cover_image' => 'games/covers/horizon-forbidden-west.jpg',
    ],
    [
        'title' => 'Terraria',
        'description' => 'Terraria è un gioco sandbox 2D che combina esplorazione, costruzione e combattimento. I giocatori iniziano con strumenti di base e possono scavare, costruire strutture, affrontare nemici e boss, e raccogliere risorse per creare oggetti sempre più potenti. Il mondo è generato proceduralmente, offrendo biomi diversi e segreti da scoprire. Con una vasta gamma di oggetti, armi e accessori, Terraria offre un\'esperienza di gioco profonda e rigiocabile, sia in solitaria che in multiplayer.',
        'release_date' => '2011-05-16',
        'developer' => 'Re-Logic',
        'consoles' => ['PC', 'PlayStation 4', 'Xbox One', 'Nintendo Switch', 'Mobile'],
        'genres' => ['sandbox', 'adventure'],
        'cover_image' => 'games/covers/terraria.jpg',
    ],
    [
        'title' => 'Resident Evil Village',
        'description' => 'Resident Evil Village è l\'ottavo capitolo della celebre saga horror di Capcom. I giocatori vestono i panni di Ethan Winters, che si avventura in un villaggio isolato e sinistro alla ricerca della figlia rapita. Il gioco offre un mix perfetto tra survival horror, azione e mistero, con un mondo gotico pieno di castelli, catacombe e creature terrificanti. La grafica mozzafiato e un sound design inquietante immergono completamente il giocatore in un\'atmosfera cupa e oppressiva. Le meccaniche di combattimento, l\'esplorazione di ambienti dettagliati e la presenza di iconici antagonisti come Lady Dimitrescu rendono Resident Evil Village un\'esperienza intensa e indimenticabile. Oltre alla campagna principale, il gioco include la modalità Mercenari per sfide aggiuntive e un DLC con contenuti extra che ampliano ulteriormente la longevità del titolo.',
        'release_date' => '2021-05-07',
        'developer' => 'Capcom',
        'consoles' => ['PC', 'PlayStation 4', 'PlayStation 5', 'Xbox One', 'Xbox Series X'],
        'genres' => ['horror', 'action'],
        'cover_image' => 'games/covers/resident-evil-village.jpg',
    ],
    [
        'title' => 'Doom Eternal',
        'description' => 'DOOM Eternal è uno sparatutto in prima persona frenetico che mette i giocatori nei panni del Doom Slayer, un guerriero leggendario in missione per salvare l\'umanità dall\'invasione demoniaca. Il gioco offre un arsenale di armi devastanti, movimenti agili e un design dei livelli che incoraggia l\'azione continua. Con una colonna sonora adrenalinica e una grafica impressionante, DOOM Eternal eleva l\'esperienza classica di DOOM a nuovi livelli di intensità.',
        'release_date' => '2020-03-20',
        'developer' => 'id Software',
        'consoles' => ['PC', 'PlayStation 4', 'PlayStation 5', 'Xbox One', 'Xbox Series X'],
        'genres' => ['shooter', 'action'],
        'cover_image' => 'games/covers/doom-eternal.jpg',
    ],
    [
        'title' => 'Assassin\'s Creed Valhalla',
        'description' => 'Assassin\'s Creed Valhalla segue le gesta di Eivor, un guerriero vichingo che guida il suo clan dalla Norvegia all\'Inghilterra del IX secolo. Il gioco combina esplorazione, combattimento e costruzione di insediamenti, offrendo una narrazione che intreccia mitologia nordica e storia. Con un sistema di progressione profondo, missioni ramificate e un mondo aperto ricco di dettagli, Valhalla offre un\'esperienza coinvolgente che espande l\'universo di Assassin\'s Creed.',
        'release_date' => '2020-11-10',
        'developer' => 'Ubisoft',
        'consoles' => ['PC', 'PlayStation 4', 'PlayStation 5', 'Xbox One', 'Xbox Series X'],
        'genres' => ['rpg', 'adventure'],
        'cover_image' => 'games/covers/assassins-creed-valhalla.jpg',
    ],
    [
        'title' => 'Overwatch',
        'description' => 'Overwatch è uno sparatutto in prima persona a squadre sviluppato da Blizzard Entertainment. I giocatori scelgono tra un roster di eroi unici, ciascuno con abilità speciali, e collaborano in partite 5v5 per completare obiettivi. Il gioco enfatizza il lavoro di squadra, la strategia e la sinergia tra i personaggi. Con aggiornamenti regolari, eventi stagionali e una comunità attiva, Overwatch offre un\'esperienza dinamica e competitiva nel panorama degli eSports.',
        'release_date' => '2016-05-24',
        'developer' => 'Blizzard Entertainment',
        'consoles' => ['PC', 'PlayStation 4', 'Xbox One', 'Nintendo Switch'],
        'genres' => ['shooter', 'action'],
        'cover_image' => 'games/covers/overwatch.jpg',
    ],
    [
        'title' => 'Bayonetta 3',
        'description' => 'Bayonetta 3 continua le avventure dell\'omonima strega, affrontando nuove minacce in un multiverso in pericolo. Il gioco introduce nuove meccaniche di combattimento, come la possibilità di controllare demoni giganti, e presenta ambientazioni diverse e nemici unici. Con un sistema di combattimento fluido, una narrazione ricca di colpi di scena e uno stile visivo distintivo, Bayonetta 3 offre un\'esperienza d\'azione intensa e spettacolare.',
        'release_date' => '2022-10-28',
        'developer' => 'PlatinumGames',
        'consoles' => ['Nintendo Switch'],
        'genres' => ['action', 'adventure'],
        'cover_image' => 'games/covers/bayonetta-3.jpg',
    ],
    [
        'title' => 'No Man\'s Sky',
        'description' => 'No Man\'s Sky è un gioco di esplorazione e sopravvivenza ambientato in un universo generato proceduralmente. I giocatori possono viaggiare tra pianeti, scoprire nuove forme di vita, costruire basi e commerciare. Con aggiornamenti regolari, il gioco ha introdotto funzionalità come il multiplayer, la costruzione di insediamenti e missioni narrative. L\'aggiornamento Beacon del 2025 ha aggiunto elementi di city-building e compatibilità con Nintendo Switch 2, ampliando ulteriormente l\'esperienza di gioco.',
        'release_date' => '2016-08-09',
        'developer' => 'Hello Games',
        'consoles' => ['PC', 'PlayStation 4', 'PlayStation 5', 'Xbox One', 'Xbox Series X'],
        'genres' => ['adventure', 'simulation'],
        'cover_image' => 'games/covers/no-mans-sky.jpg',
    ],
    [
        'title' => 'Celeste',
        'description' => 'Celeste è un platformer 2D che segue la storia di Madeline, una giovane donna che cerca di scalare la montagna Celeste. Il gioco combina meccaniche di salto precise con una narrazione toccante che esplora temi di ansia, depressione e autoaccettazione. Con una colonna sonora evocativa, livelli progettati con cura e una difficoltà bilanciata, Celeste offre un\'esperienza emozionante e gratificante.',
        'release_date' => '2018-01-25',
        'developer' => 'Maddy Makes Games',
        'consoles' => ['PC', 'PlayStation 4', 'Xbox One', 'Nintendo Switch'],
        'genres' => ['platform', 'adventure'],
        'cover_image' => 'games/covers/celeste.jpg',
    ],
];
